choco install adobereader -y
choco install googlechrome -y
choco install firefox -y
choco install notepadplusplus.install -y
choco install 7zip.install -y
choco install vlc -y
choco install paint.net -y
choco install microsoft-windows-terminal -y
choco install libreoffice-fresh -y